---
title: "spotifyr_test"
author: "Dash Chin"
date: "10/23/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
library(tidyverse) 
library(spotifyr) 
library(knitr) 
library(lubridate)

```

```{r examples}

travis_scott <- get_artist_audio_features('travis scott')

travis_scott %>% 
    count(key_mode, sort = TRUE)
    # head(5) %>% 
    # kable()

Sys.setenv(SPOTIFY_CLIENT_ID = '8a8f9963e2b84ea485694d8a99919904')

get_my_recently_played(limit = 5) %>% 
    mutate(artist.name = map_chr(track.artists, function(x) x$name[1]),
           played_at = as_datetime(played_at)) %>% 
    select(track.name, artist.name, track.album.name, played_at) %>% 
    kable()

get_my_top_artists_or_tracks(type = 'artists', time_range = 'long_term', limit = 5) %>% 
    select(name, genres) %>% 
    rowwise %>% 
    mutate(genres = paste(genres, collapse = ', ')) %>% 
    ungroup

get_my_top_artists_or_tracks(type = 'tracks', time_range = 'short_term', limit = 5) %>% 
    mutate(artist.name = map_chr(artists, function(x) x$name[1])) %>% 
    select(name, artist.name, album.name)  


playlists <- get_user_playlists("korealegend")
View(playlists) 



```

