---
title: "test.Rmd"
author: "Dash Chin"
date: "11/29/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rstanarm) 
library(tidyverse)
library(gt)
library(broom.mixed)
library(gtsummary) 
library(dplyr)
```


``` {r}

# BIG SET

full_set <- Kanye_streams %>% 
  mutate(collabs = str_count(With, ",") + 1) %>%  
  select(Track, Streams, With, collabs) %>%  
  rename(track_name = Track) %>%  
  full_join(kanye, by = "track_name") %>%  
  distinct(track_name, .keep_all = TRUE) 
```


```{r}
stan_glm(data = kanye, refresh = 0, loudness ~ album_release_date) %>%
tbl_regression(intercept = FALSE) %>%
as_gt() %>%
tab_header(title = "Regression of Loudness by Release Date",
subtitle = "The Effect of Time on Loudness") 

# gt::tab_source_note(gt::md("Source: https://voteview.com/data"))
```
```{r}
kanye <- get_artist_audio_features('kanye west') %>%  
  print()

model1 <- stan_glm(data = kanye, refresh = 0, loudness ~ album_release_year) 

new_obs <- tibble(album_release_year = 2019)

posterior_epred(model1, newdata = new_obs) %>%  
  as_tibble() %>%  
  mutate_all(as.numeric) %>%  
  ggplot(aes(x = `1`)) + 
  geom_histogram(aes(y = after_stat(count/sum(count))))


```

# Popularity

```{r}


library(stringr)

library(plotly)

# Streams vs Features. (Plotly)

streamsf_plot <- Kanye_streams %>% 
  mutate(collabs = str_count(With, ",") + 1) %>%  
  select(Track, Streams, With, collabs) %>% 
  remove_missing(na.rm = TRUE) %>% 
  ggplot(aes(x = collabs, y = Streams, text = paste(
               Track 
               ))) + 
  geom_point(alpha = 0.5, colour = "red") + 
  labs(x = "Number of Features", 
       y = "Number of Streams", 
       title = "Streams as a function of features", 
       subtitle = "Including singles.")

ggplotly(streamsf_plot, tooltip = "text")

```




``` {r}

# Streams and Loudness (GIF)

p <- streamsAndStats %>%  
  ggplot(aes(x = loudness, y = Streams, color = album_name))+ 
  geom_point() +
  theme_bw() + 
  labs(title = 'Year: {frame_time}', 
       x = 'Loudness (dB)', 
       y = 'Streams',
       subtitle = "Is Louder Better?") +
  transition_time(as.integer(album_release_year)) +  
  ease_aes('linear')  

anim_save("outfile.gif", animate(p))

```


```{r}

p2 <- full_set %>%  
  subset(!is.na(album_name)) %>%  
  subset(!is.na(Streams)) %>% 
  subset(!is.na(danceability)) %>%
  select(track_name,album_name, Streams, danceability) %>%  
  group_by(album_name) %>% 
  ggplot(aes(x = danceability, y = Streams)) +
  geom_point(aes(colour = album_name, group = 1L)) +
  theme_bw() + 
  labs(title = "Relationship Between Danceability and Streaming, by Album", x = "Danceability", y = "Streams") +
  transition_states(album_name,
                    transition_length = 2,
                    state_length = 1) 


  
  summarize(total_streams = sum(Streams), .groups = "keep") %>%  
  arrange(total_streams) 

```
```{r}

wc_tibble<-full_set %>%  
  subset(!is.na(Streams)) %>%    
  select(track_name, Streams)




wordcloud2(data = wc_tibble, 
           fontFamily = "sans-serif", 
           color = rep_len(c("plum","orange", "lightblue", "orange"), 
               nrow(wc_tibble)))
```


# Network 

```{r}

# Histogram multiple variables  

histo_big <- full_set%>% 
  mutate(collabs = str_count(With, ",") + 1) %>% 
            subset(!is.na(danceability)) %>%
            subset(!is.na(Streams)) %>%
  mutate(duration_seconds = duration_ms / 1000) %>% 
  select(Streams, danceability, energy, key, loudness, mode, speechiness, acousticness, instrumentalness, liveness, tempo, duration_seconds, duration_ms) 

stan_glm(data = histo_big, 
         refresh = 0, 
         formula = Streams ~ danceability +  key + loudness + mode + speechiness + acousticness  + liveness + tempo + duration_ms)



```


```{r}
full_set <- Kanye_streams %>% 
            mutate(collabs = str_count(With, ",") + 1) %>%  
            select(Track, Streams, With, collabs) %>%  
            rename(track_name = Track) %>%  
            full_join(kanye, by = "track_name") %>%  
            distinct(track_name, .keep_all = TRUE) 
        
         p2 <- full_set %>%  
            subset(!is.na(album_name)) %>%  
            subset(!is.na(Streams)) %>% 
            subset(!is.na(danceability)) %>%
            select(track_name,album_name, Streams, danceability) %>%  
            group_by(album_name) %>% 
            ggplot(aes(x = danceability, y = Streams)) +
            geom_point(aes(color = "blue"))+
            theme_bw() + 
            labs(title = "Relationship Between Danceability and Streaming, by Album", 
                 x = "Danceability", 
                 y = "Streams") +
            transition_states(album_name,
                              transition_length = 2,
                              state_length = 1)
        
        
        anim_save("streamdance.gif", animate(p2))
        
```

``
```

